### ISSUE TITLE
Bluebird version 3 support

### ISSUE THREAD

**Issue by solsend2l** [koajs/koala#18] opened 2015-11-17 13:55 UTC
http://bluebirdjs.com/docs/new-in-bluebird-3.html

**Comment by nickmccurdy** [comment] 2017-09-03 21:27
Note sure if this is a duplicate of #34 now. Also, I think we should move to native Promises instead of updating Bluebird. Thoughts?

**Comment by nickmccurdy** [comment] 2017-09-04 02:38
Nevermind, looks like we're already using Bluebird 3. Let me know if there are any issues with it.

**Closed by nickmccurdy** 2017-09-04 02:38 UTC
Labels: maintenance

**Comment by doug-wade** [comment] 2017-09-05 23:11
@nickmccurdy I would definitely be in favor of removing bluebird in favor of native promises.
